version: "3.9"

services:
  backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./BE:/usr/src/app
    environment:
      - NODE_ENV=development
    command: npm run start:dev

  frontend:
    build:
      context: ./FE
      dockerfile: Dockerfile
      args:
        VITE_APP_API_BASE_URL: http://localhost:3000
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    environment:
      - VITE_APP_API_BASE_URL=http://localhost:3000

networks:
  default:
    driver: bridge